enum ActionType {
    FETCH_POST_REQUEST = "FETCH_POST_REQUEST",
    FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS",
    FETCH_POST_FAILED = "FETCH_POST_FAILED",
    SEARCH_POSTS = 'SEARCH_POSTS'
}

export default ActionType
